### ISSUE TITLE
Multipart uploads fail with minio client due to mismatched etags

### ISSUE THREAD

**Issue by tasdomas** [johannesboyne/gofakes3#51]
I was trying to use `gofakes3` to test the use of the `https://pkg.go.dev/github.com/minio/minio-go/v7#Client` in a package. However, I've found that multipart uploads fail due to a failing test [here](https://github.com/johannesboyne/gofakes3/blob/master/uploader.go#L502).

The condition fails because `inPart.ETag` (from the xml doc) is not quoted and `upPart.ETag` (from the header) is.

Even though RFC7232 specifies that etags are always quoted, aws s3 docs are not clean on whether the etag should be quoted in the xml document.

**Comment by johannesboyne** [comment]
Hi @tasdomas 
Thank's a lot for the contribution, seems to be a relevant change. Thanks!
