### ISSUE TITLE
Race condition listing objects while deleting

### ISSUE THREAD

**Issue by samc1213** [johannesboyne/gofakes3#89]
I have some code in production which, in parallel, lists objects in a prefix, and then deletes them. Gofakes3 appears to not work correctly for this use case. See the test [here](https://github.com/johannesboyne/gofakes3/compare/master...samc1213:gofakes3:parallel_list_delete). If run repeatedly, eventually it will fail with `gofakes3_test.go:230: All objects should be deleted, got 1 left`. Can someone spot where the issue is? `s3mem/backend` appears to be thread-safe, but maybe the issue is occurring at the bucket page listing level?

**Comment by johannesboyne** [comment]
Hi @samc1213 interesting case! Will have to dig deeper to fully check where such a race condition could appear. Thanks a lot for adding the test case, that helps a lot for debugging. If you in the meantime will find a fix, feel invited to open a PR!

**Comment by johannesboyne** [comment]
@samc1213 could you please test whether @rodaine 's patch https://github.com/johannesboyne/gofakes3/pull/90 also fixes the race condition you brought up?

I just tested it on my machine (apple silicon) and your test case runs without any issue now. Even with `20,000` files! If so, happy to integrate your Test-Case into the main branch!

**Comment by johannesboyne** [comment]
Please re-open if it still exists.
